version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - enrollment
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - enrollment
  tests:
      image: golang:1.20-alpine
      volumes:
        - ./tests:/code
      working_dir: /code
      environment:
        host: "http://app:8080"
      links:
        - app
      networks:
        - enrollment
      command: /bin/sh -c "go mod tidy && go test -v"

networks:
  enrollment:
    driver: bridge